/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CerbySwapLP1155V1Contract } from "./CerbySwapLP1155V1";
import { CerbySwapV1Contract } from "./CerbySwapV1";
import { MigrationsContract } from "./Migrations";
import { TestCerUsdTokenContract } from "./TestCerUsdToken";
import { TestCerbyTokenContract } from "./TestCerbyToken";
import { TestUsdcTokenContract } from "./TestUsdcToken";
import { WETH9Contract } from "./WETH9";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "CerbySwapLP1155V1"): CerbySwapLP1155V1Contract;
      require(name: "CerbySwapV1"): CerbySwapV1Contract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "TestCerUsdToken"): TestCerUsdTokenContract;
      require(name: "TestCerbyToken"): TestCerbyTokenContract;
      require(name: "TestUsdcToken"): TestUsdcTokenContract;
      require(name: "WETH9"): WETH9Contract;
    }
  }
}

export {
  CerbySwapLP1155V1Contract,
  CerbySwapLP1155V1Instance,
} from "./CerbySwapLP1155V1";
export { CerbySwapV1Contract, CerbySwapV1Instance } from "./CerbySwapV1";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  TestCerUsdTokenContract,
  TestCerUsdTokenInstance,
} from "./TestCerUsdToken";
export {
  TestCerbyTokenContract,
  TestCerbyTokenInstance,
} from "./TestCerbyToken";
export { TestUsdcTokenContract, TestUsdcTokenInstance } from "./TestUsdcToken";
export { WETH9Contract, WETH9Instance } from "./WETH9";
